### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mntext** [NFT-wiki/NFT-marketplace#1]
- [ ] List all NFT marketplace
- [ ] Compare their difference
- [ ] Improve and Update
- [ ] Auto Update Flow
